apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-features-matteo-button-in-cluster
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: thesis-app-backend-features-matteo-button
  project: default
  source:
    path: kustomize/overlays/backend/features/matteo-button/
    repoURL: https://github.com/mattedamo/thesis-app-infrastructure.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
