apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-features-second-feature-in-cluster
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: thesis-app-backend-features-second-feature
  project: default
  source:
    path: kustomize/overlays/backend/features/second-feature/
    repoURL: https://github.com/mattedamo/thesis-app-infrastructure.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
