apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: backend-features-f1-second-cluster
  namespace: argocd
spec:
  destination:
    name: second-cluster
    namespace: thesis-app-backend-features-f1
  project: default
  source:
    path: kustomize/overlays/backend/features/f1/
    repoURL: https://github.com/mattedamo/thesis-app-infrastructure.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
