apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: prod-second-cluter
  namespace: argocd
spec:
  destination:
    name: second-cluter
    namespace: thesis-app-prod
  project: default
  source:
    path: kustomize/overlays/prod/
    repoURL: https://github.com/mattedamo/thesis-app-infrastructure.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
