name: update-manifest
on: 
  workflow_dispatch:
    inputs:
      code-branch:
        description: 'branch of code repo'
        required: true
      tier: 
        description: 'the tier of the code repo'
        required: true
      app-name:
        description: 'name of the app'
        required: true
      code-repo:
        description: 'name of code repo'
        required: true
      

jobs:
  update-manifest:
    name: Update manifest
    runs-on: ubuntu-latest
    
    steps:
      
      - name: set environment variables
        uses: allenevans/set-env@v2.0.0
        with:
          TIER: ${{ github.event.inputs.tier}}
          CODE_BRANCH: ${{ github.event.inputs.code-branch}}
          APP_NAME: ${{ github.event.inputs.app_name }}
          SOURCE_REPO_URL : ${{ secrets.SOURCE_REPO_URL }}
          CODE_REPO: ${{ github.event.inputs.code-repo}}

      - name: Check out code
        uses: actions/checkout@v2
      
      - name: Checkout code repo
        uses: actions/checkout@v2
        with:
            repository: mattedamo/${{ github.event.inputs.repo-name}}
            token: ${{secrets.TOKEN_GITHUB_DISPATCHER}}
            ref: ${{ github.event.inputs.code-branch}}
            path: code-repo
      - run: cp code-repo/input.yaml ./input.yaml
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with: 
          python-version: "3.x"

      - run: pip install PyYAML
        name: Install py dependencies
        
      - name: Update manifests
        run: python update-manifest.py
        
      
      - run: rm -f input.yaml
        
      - run: rm -rf code-repo/

      - name: Add and commit changes
        uses: EndBug/add-and-commit@v6
        with:
          message: 'updated manifests'
  