name: update-manifest
on: 
  workflow_dispatch:
    inputs:
      docker-image-tag:
        description: 'this is the docker tag build in the code workflow'     
        required: true
      code-branch:
        description: 'branch of code repo'
        required: true
      repo-name: 
        description: 'name of code repo'
        required: true
      tier: 
        description: 'the tier of the code repo'
        required: true
      docker-frontend-repo:
        description: 'the repo name on dockerhub for the frontend image'
        required: true
      docker-backend-repo:
        description: 'the repo name on dockerhub for the backend image'
        required: true
      

jobs:
  update-values:
    name: Update kustomize
    runs-on: ubuntu-latest
    
    steps:
      
      - name: set environment variables
        uses: allenevans/set-env@v2.0.0
        with:
          DOCKER_TAG: ${{ github.event.inputs.docker-image-tag}}
          CODE_BRANCH:  ${{ github.event.inputs.code-branch}}
          CODE_REPO_NAME: ${{ github.event.inputs.repo-name}}
          TIER: ${{ github.event.inputs.tier}}
          DOCKER_BACKEND_REPO: ${{ github.event.inputs.docker-backend-repo}}
          DOCKER_FRONTEND_REPO: ${{ github.event.inputs.docker-frontend-repo}}
          DOCKER_USER: ${{secrets.DOCKER_USERNAME}}

      - name: Check out code
        uses: actions/checkout@v2
      
      - name: Checkout code repo
        uses: actions/checkout@v2
        with:
            repository: mattedamo/${{ github.event.inputs.repo-name}}
            token: ${{secrets.TOKEN_GITHUB_DISPATCHER}}
            ref: ${{ github.event.inputs.code-branch}}
            path: code-repo
      - run: cp code-repo/input.yaml ./input.yaml
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with: 
          python-version: "3.x"

      - run: pip install PyYAML
        name: Install py dependencies
        
      - name: Create kustomize overlays dir, if necessary
        run: python overlays-dir-creation.py
        
      - run: python update-overlays.py
        name: Run python script, update kustomize overlays
        
      - run: python update-docker-img.py
        name: Run update docker image
      
      - run: rm -f input.yaml
        
      - run: rm -rf code-repo/

      - name: Add and commit changes
        uses: EndBug/add-and-commit@v6
        with:
          message: 'updated kustomize files'
  
  trigger-workflow:
    name: Trigger workflow in ArgoCD repo
    runs-on: ubuntu-latest
    needs: update-values
    steps:
      
      - name: Trigger infrastructure repo workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: create-manifest
          ref: master
          inputs: '{"docker-image-tag" : "{{ github.sha }}-${{steps.extract_branch.outputs.branch}}", "code-branch" : "${{steps.extract_branch.outputs.branch}}", "repo-name" : "${{ github.event.repository.name }}", "docker-frontend-repo" : "${{secrets.DOCKER_FRONTEND_REPO}},"docker-backend-repo" : "${{secrets.DOCKER_BACKEND_REPO}}", "tier" : "${{secrets.TIER}}"}'
          repo: mattedamo/thesis-argocd
          token: ${{ secrets.TOKEN_GITHUB_DISPATCHER }}

